[2025-04-26 03:19:30 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2025-04-26 03:19:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2025-04-26 03:19:30 +0000] [1] [INFO] Using worker: sync
[2025-04-26 03:19:31 +0000] [7] [INFO] Booting worker with pid: 7
[2025-04-26 03:25:01 +0000] [1] [INFO] Handling signal: term
[2025-04-26 03:25:01 +0000] [7] [INFO] Worker exiting (pid: 7)
[2025-04-26 03:25:01 +0000] [1] [INFO] Shutting down: Master
[2025-04-26 03:26:01 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2025-04-26 03:26:01 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2025-04-26 03:26:01 +0000] [1] [INFO] Using worker: sync
[2025-04-26 03:26:01 +0000] [6] [INFO] Booting worker with pid: 6
Not Found: /favicon.ico
[2025-04-26 03:34:42 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:6)
[2025-04-26 03:34:42 +0000] [6] [INFO] Worker exiting (pid: 6)
[2025-04-26 03:34:42 +0000] [1] [ERROR] Worker (pid:6) exited with code 1
[2025-04-26 03:34:42 +0000] [1] [ERROR] Worker (pid:6) exited with code 1.
[2025-04-26 03:34:42 +0000] [7] [INFO] Booting worker with pid: 7
Not Found: /favicon.ico
Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Bad Request: /*
Not Found: /favicon.ico
Not Found: /login
